### Get all books
GET http://localhost:8080/api/books
Accept: application/json

### Get book by id
GET http://localhost:8080/api/books/5
Accept: application/json

### Create book
POST http://localhost:8080/api/books
Content-Type: application/json
Accept: application/json

{
  "author": "Stephen King",
  "title": "Shining",
  "rentalDate": "2021-02-28"
}

### Validation
POST http://localhost:8080/api/books
Content-Type: application/json
Accept: application/json

{
  "author": "",
  "title": "Shining",
  "rentalDate": "2021-02-28"
}

### Lend book
POST http://localhost:8080/api/books/7/reader/3
Content-Type: application/json
Accept: application/json

### lend book update
PUT http://localhost:8080/api/books/7/reader/3
Content-Type: application/json
Accept: application/json

{
"author": "Stephen King",
"title": "Christine",
"rentalDate": "2021-05-12"
}

###
DELETE http://localhost:8080/api/books/5